In [13]:
from tensorflow import keras
from keras.models import Model
from keras import layers
from keras.layers import Dense, Input, BatchNormalization, Activation
from keras.layers import Conv2D, SeparableConv2D, MaxPooling2D, GlobalAveragePooling2D, GlobalMaxPooling2D
#from keras.applications.imagenet_utils import _obtain_input_shape
#from keras.utils.data_utils import get_file
from sklearn.model_selection import KFold
from keras.datasets import mnist
from PIL import Image
# for creating a one hot vector for labels
#from keras.utils import np_utils
from IPython.display import display, Image
#import the models
from keras import Model
#add layers
from keras import layers
#add optimizer
from keras import optimizers
#add loss function 
from keras import losses
import random

import keras
import numpy as np
import pandas as pd 
import os
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, Dropout, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image
import os
import numpy as np
import matplotlib.pyplot as plt
import cv2
 

In [14]:
from tensorflow import keras
from keras.models import Model
from keras.layers import Dense, Input, BatchNormalization, Activation
from keras.layers import Conv2D, SeparableConv2D, MaxPooling2D, GlobalAveragePooling2D
from IPython.core.display import display, HTML
import sys

x = []
label = []
x_validation = []
label_validation = []
x_test = []
label_test = []



csv_file = pd.read_csv("/kaggle/input/tea-image-dataset-nlmd-filtered/splited_into_5_fold.csv")
img_size = 299

folded = csv_file.groupby("fold")
temp_image_name = ""
temp_image = []
for i,j in folded:
    if i == 0: # testing
        print("fold "+str(i))
        cat = j.groupby("category")
        for k,l in cat:
            if k == "Brown_blight":
                brown_blight_image_name = l['image_name']
                brown_blight_link = "/kaggle/input/tea-image-dataset-nlmd-filtered/filtered/filtered/non_local_means_denoising/Brown_blight"
                
                for m in brown_blight_image_name:
                    brown_blight_image = cv2.imread(brown_blight_link + '/'+"nlmd_"+m)
                    brown_blight_image = cv2.resize( brown_blight_image , ( img_size , img_size ))
                    """
                    if len(temp_image) == 0:
                        temp_image_name = m
                        temp_image = brown_blight_image
                    """
                    x_test.append(brown_blight_image)
                    label_test.append([0])
                print(len(x_test)," ",len(label_test))
                    
            if k == "Grey_blight":
                grey_blight_image_name = l['image_name']    
                grey_blight_link = "/kaggle/input/tea-image-dataset-nlmd-filtered/filtered/filtered/non_local_means_denoising/Grey_blight"

                for m in grey_blight_image_name:
                    grey_blight_image = cv2.imread(grey_blight_link + '/'+"nlmd_"+m)
                    grey_blight_image = cv2.resize( grey_blight_image , ( img_size , img_size ))
                    """
                    if len(temp_image) == 0:
                        temp_image_name = m
                        temp_image = grey_blight_image
                    """
                    x_test.append(grey_blight_image)
                    label_test.append([1])
                print(len(x_test)," ",len(label_test))
                    
            if k == "Healthy":
                healthy_image_name = l['image_name']    
                healthy_link = "/kaggle/input/tea-image-dataset-nlmd-filtered/filtered/filtered/non_local_means_denoising/Healthy"

                for m in healthy_image_name:
                    healthy_image = cv2.imread(healthy_link + '/'+"nlmd_"+m)
                    healthy_image = cv2.resize( healthy_image , ( img_size , img_size ))
                    """
                    if len(temp_image) == 0:
                        temp_image_name = m
                        temp_image = healthy_image
                    """
                    x_test.append( healthy_image)
                    label_test.append([2])
                print(len(x_test)," ",len(label_test))

            if k == "Red_rust":
                red_rust_image_name = l['image_name']
                red_rust_link = "/kaggle/input/tea-image-dataset-nlmd-filtered/filtered/filtered/non_local_means_denoising/Red_rust"

                for m in red_rust_image_name:
                    red_rust_image = cv2.imread(red_rust_link+ '/' + "nlmd_"+m)
                    red_rust_image = cv2.resize(red_rust_image, (img_size, img_size))
                    x_test.append(red_rust_image)
                    label_test.append([3])
                print(len(x_test)," ", len(label_test))
            
    
    elif i == 1: # validation
        print("fold "+str(i))
        cat = j.groupby("category")
        for k,l in cat:
            if k == "Brown_blight":
                brown_blight_image_name = l['image_name']
                brown_blight_link = "/kaggle/input/tea-image-dataset-nlmd-filtered/filtered/filtered/non_local_means_denoising/Brown_blight"
                
                for m in brown_blight_image_name:
                    brown_blight_image = cv2.imread(brown_blight_link + '/'+"nlmd_"+m)
                    brown_blight_image = cv2.resize(brown_blight_image , ( img_size , img_size ))
                    """
                    if len(temp_image) == 0:
                        temp_image_name = m
                        temp_image = brown_blight_image
                    """
                    x_validation.append(brown_blight_image)
                    label_validation.append([0])
                print(len(x_validation)," ",len(label_validation))
                    
            if k == "Grey_blight":
                grey_blight_image_name = l['image_name']    
                grey_blight_link = "/kaggle/input/tea-image-dataset-nlmd-filtered/filtered/filtered/non_local_means_denoising/Grey_blight"

                for m in grey_blight_image_name:
                    grey_blight_image = cv2.imread(grey_blight_link + '/'+"nlmd_"+m)
                    grey_blight_image = cv2.resize( grey_blight_image , ( img_size , img_size ))
                    """
                    if len(temp_image) == 0:
                        temp_image_name = m
                        temp_image = grey_blight_image
                    """
                    x_validation.append(grey_blight_image)
                    label_validation.append([1])
                print(len(x_validation)," ",len(label_validation))
                    
            if k == "Healthy":
                healthy_image_name = l['image_name']    
                healthy_link = "/kaggle/input/tea-image-dataset-nlmd-filtered/filtered/filtered/non_local_means_denoising/Healthy"

                for m in healthy_image_name:
                    healthy_image = cv2.imread(healthy_link + '/'+"nlmd_"+m)
                    healthy_image =  cv2.resize(healthy_image , ( img_size , img_size ))
                    if len(temp_image) == 0:
                        temp_image_name = m
                        temp_image = healthy_image
                    x_validation.append( healthy_image)
                    label_validation.append([2])
                print(len(x_validation)," ",len(label_validation))
                
            if k == "Red_rust":
                red_rust_image_name = l['image_name']
                red_rust_link = "/kaggle/input/tea-image-dataset-nlmd-filtered/filtered/filtered/non_local_means_denoising/Red_rust"

                for m in red_rust_image_name:
                    red_rust_image = cv2.imread(red_rust_link+ '/' + "nlmd_"+m)
                    red_rust_image = cv2.resize(red_rust_image, (img_size, img_size))
                    x_validation.append(red_rust_image)
                    label_validation.append([3])
                print(len(x_validation)," ", len(label_validation))
            

    else: # training
        print("fold "+str(i))
        cat = j.groupby("category")
        for k,l in cat:
            if k == "Brown_blight":
                brown_blight_image_name = l['image_name']
                brown_blight_link = "/kaggle/input/tea-image-dataset-nlmd-filtered/filtered/filtered/non_local_means_denoising/Brown_blight"
                
                for m in brown_blight_image_name:
                    brown_blight_image = cv2.imread(brown_blight_link + '/'+"nlmd_"+m)
                    brown_blight_image = cv2.resize(brown_blight_image , ( img_size , img_size ))
                    """
                    if len(temp_image) == 0:
                        temp_image_name = m
                        temp_image = brown_blight_image
                    """
                    x.append(brown_blight_image)
                    label.append([0])
                print(len(x)," ",len(label))
            if k == "Grey_blight":
                grey_blight_image_name = l['image_name']    
                grey_blight_link = "/kaggle/input/tea-image-dataset-nlmd-filtered/filtered/filtered/non_local_means_denoising/Grey_blight"

                for m in grey_blight_image_name:
                    grey_blight_image = cv2.imread(grey_blight_link + '/'+"nlmd_"+m)
                    grey_blight_image = cv2.resize( grey_blight_image , ( img_size , img_size ))
                    """
                    if len(temp_image) == 0:
                        temp_image_name = m
                        temp_image = grey_blight_image
                    """
                    x.append(grey_blight_image)
                    label.append([1])
                print(len(x)," ",len(label))
                    
            if k == "Healthy":
                healthy_image_name = l['image_name']    
                healthy_link = "/kaggle/input/tea-image-dataset-nlmd-filtered/filtered/filtered/non_local_means_denoising/Healthy"

                for m in healthy_image_name:
                    healthy_image = cv2.imread(healthy_link + '/'+"nlmd_"+m)
                    healthy_image =  cv2.resize(healthy_image , ( img_size , img_size ))
                    if len(temp_image) == 0:
                        temp_image_name = m
                        temp_image = healthy_image
                    x.append( healthy_image)
                    label.append([2])
                print(len(x)," ",len(label))
                
            if k == "Red_rust":
                red_rust_image_name = l['image_name']
                red_rust_link = "/kaggle/input/tea-image-dataset-nlmd-filtered/filtered/filtered/non_local_means_denoising/Red_rust"

                for m in red_rust_image_name:
                    red_rust_image = cv2.imread(red_rust_link+ '/' + "nlmd_"+m)
                    red_rust_image = cv2.resize(red_rust_image, (img_size, img_size))
                    x.append(red_rust_image)
                    label.append([3])
                print(len(x)," ", len(label))
            





fold 0
159   159
329   329
491   491
649   649
fold 1
159   159
328   328
490   490
648   648
fold 2
158   158
327   327
489   489
646   646
fold 3
804   804
973   973
1135   1135
1292   1292
fold 4
1450   1450
1619   1619
1780   1780
1937   1937


In [15]:
x = np.asarray(x)
x_validation = np.asarray(x_validation)
x_test = np.asarray(x_test)

print(len(x)," ", len(x_validation)," ", len(x_test))

1937   648   649


In [16]:
from tensorflow.keras.utils import to_categorical 

label = np.array(label)
label = to_categorical(label , 4 )
print(len(label))



label = np.array(label)
label_validation = to_categorical(label_validation , 4 )
print(len(label_validation))

label = np.array(label)
label_test = to_categorical(label_test , 4 )
print(len(label_test))

1937
648
649


In [17]:
from tensorflow.keras.models import load_model

model_path = "/kaggle/input/tea-image-testing/initial_training_validation/xception_tea_leaves_nlmd_filtered (1).keras"
model = load_model(model_path)
print("Model loaded successfully!")

Model loaded successfully!


In [18]:


test_loss, test_accuracy = model.evaluate(x_test, label_test, verbose=1)
print(f"Test Accuracy: {test_accuracy:.4f}")
print(f"Test Loss: {test_loss:.4f}")

21/21 ━━━━━━━━━━━━━━━━━━━━ 9s 275ms/step - accuracy: 0.9394 - loss: 0.2227
Test Accuracy: 0.9522
Test Loss: 0.1670


In [19]:


test_loss, test_accuracy = model.evaluate(x_validation, label_validation, verbose=1)
print(f"Test Accuracy: {test_accuracy:.4f}")
print(f"Test Loss: {test_loss:.4f}")

21/21 ━━━━━━━━━━━━━━━━━━━━ 6s 275ms/step - accuracy: 0.9294 - loss: 0.2882
Test Accuracy: 0.9537
Test Loss: 0.1812


In [20]:
predictions = model.predict(x_test)
predicted_classes = np.argmax(predictions, axis=1)
true_classes = np.argmax(label_test, axis=1)

21/21 ━━━━━━━━━━━━━━━━━━━━ 8s 314ms/step


In [21]:
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

print("\nClassification Report:")
print(classification_report(true_classes, predicted_classes))

# Generate a confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(true_classes, predicted_classes))


Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.93      0.94       159
           1       0.93      0.89      0.91       170
           2       0.99      1.00      1.00       162
           3       0.94      0.99      0.96       158

    accuracy                           0.95       649
   macro avg       0.95      0.95      0.95       649
weighted avg       0.95      0.95      0.95       649


Confusion Matrix:
[[148  11   0   0]
 [  8 152   0  10]
 [  0   0 162   0]
 [  0   1   1 156]]
